version: '3'
services:
  front:
    build:
      context: './react-docker'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: reactjs-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - docker-mern-stack-network
    volumes:
      - ./react-docker:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: './express-docker'
      dockerfile: Dockerfile
    ports:
      - 5500:5500
    container_name: expressjs-container
    networks:
      - docker-mern-stack-network
    volumes:
      - ./express-docker:/app
      - /app/node_modules
    depends_on:
      - mongodbprod
  mongodbprod:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb-container
    networks:
      - docker-mern-stack-network
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=products
networks:
  docker-mern-stack-network:
volumes:
  mongoData: